#!/usr/bin/env bash

PHP_CS_FIXER="$HOME/.bin/php-cs-fixer"
PHP_CS_CONFIG="$HOME/.bin/.php-cs-fixer.php"
CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.php')

PINT='./vendor/bin/pint'
if [ -n "$CHANGED_FILES" ]; then
    if [ -f $PINT ]; then
        echo "pint pre commit hook start"
        $PINT $CHANGED_FILES;
        git add $CHANGED_FILES;
        echo "pint pre commit hook finish"
    else
        echo "php-cs-fixer pre commit hook start"
        $PHP_CS_FIXER fix --using-cache=no --verbose --config "$PHP_CS_CONFIG" $CHANGED_FILES;
        git add $CHANGED_FILES;
        echo "php-cs-fixer pre commit hook finish"
    fi
fi

