#!/usr/bin/env bash

PHP_CS_FIXER="$HOME/.bin/php-cs-fixer"
PHP_CS_CONFIG="$HOME/.bin/.php-cs-fixer.php"
CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.php')

if [ -n "$CHANGED_FILES" ]; then
    echo "php-cs-fixer pre commit hook start"
    $PHP_CS_FIXER fix --using-cache=no --verbose --config "$PHP_CS_CONFIG" $CHANGED_FILES;
    git add $CHANGED_FILES;
    echo "php-cs-fixer pre commit hook finish"
fi

